
// This file is automatically generated by Firebase Studio.
// Do not edit this file manually.

// Follow the instructions in the README file to configure this for your own project.
// If you are using the demo project, you can ignore this file.

const firebaseConfig = {
  projectId: "studio-7548244915-aa0e7",
  appId: "1:1040599678886:web:a72ae7f50af2747a119967",
  apiKey: "AIzaSyBLXs0P2K9TKzEE-tOreXyNyjgVSrjby4c",
  authDomain: "studio-7548244915-aa0e7.firebaseapp.com",
  messagingSenderId: "1040599678886"
};

export function getFirebaseConfig() {
  if (!firebaseConfig.apiKey) {
    throw new Error('Missing Firebase config: NEXT_PUBLIC_FIREBASE_API_KEY')
  }
  return firebaseConfig
}
