
declare namespace NodeJS {
  interface ProcessEnv {
    NEXT_PUBLIC_APP_URL?: string;
    LEMONSQUEEZY_API_KEY: string;
    LEMONSQUEEZY_STORE_ID: string;
    LEMONSQUEEZY_WEBHOOK_SECRET: string;
    NEXT_PUBLIC_LEMONSQUEEZY_NEWSLETTER_VARIANT_ID: string;
    NEXT_PUBLIC_LEMONSQUEEZY_BUILDER_MONTHLY_VARIANT_ID: string;
    NEXT_PUBLIC_LEMONSQUEEZY_BUILDER_ANNUALLY_VARIANT_ID: string;
    NEXT_PUBLIC_LEMONSQUEEZY_ARCHITECT_MONTHLY_VARIANT_ID: string;
    NEXT_PUBLIC_LEMONSQUEEZY_ARCHITECT_ANNUALLY_VARIANT_ID: string;
    GOOGLE_APPLICATION_CREDENTIALS: string;
  }
}
